### ISSUE TITLE
Bug with the function DropBox-Upload 

### ISSUE THREAD

**Issue by oasis4** [atomiczsec/My-Payloads#3]
I got the error: 
Invoke-RestMethod : {"error_summary": "missing_scope/...", "error": {".tag": "missing_scope", "required_scope":
"files.content.write"}}
In Zeile:57 Zeichen:5
+     Invoke-RestMethod -Uri https://content.dropboxapi.com/2/files/upl ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
Invoke-RestMethod : {"error_summary": "missing_scope/...", "error": {".tag": "missing_scope", "required_scope":
"files.content.write"}}
In Zeile:57 Zeichen:5
+     Invoke-RestMethod -Uri https://content.dropboxapi.com/2/files/upl ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by atomiczsec** [comment]
The error message you received suggests that you are encountering a scope issue while using the Invoke-RestMethod cmdlet in PowerShell to upload a file to Dropbox's API. More specifically, the error indicates that the required scope "files.content.write" is missing.

In order to upload files to Dropbox using the Dropbox API, you need to include the necessary scope to authorize your application to perform the write operation. Scopes define the level of access and permissions granted to your application.

To resolve this issue, you should ensure that you have properly configured your Dropbox API app with the correct scopes. Make sure that your app has been granted the "files.content.write" scope, which allows it to write/upload files to Dropbox. You may need to check your app's configuration and adjust the scope settings accordingly.
